### ISSUE TITLE
images

### ISSUE THREAD

**Issue by miyako** [miyako/4d-plugin-phonetic#1]
<img width="800" alt="mac" src="https://cloud.githubusercontent.com/assets/1725068/16212404/4f7d1220-3782-11e6-86ae-c2eb37c5bfec.png">
<img width="646" alt="win" src="https://cloud.githubusercontent.com/assets/1725068/16212405/533a2b78-3782-11e6-953b-fafb687102a6.png">

**Comment by 4D-JP** [comment]
<img width="800" alt="mac" src="https://cloud.githubusercontent.com/assets/10509075/16212712/97f855ee-3784-11e6-9547-0768e6ac3c9f.png">
